[build]
builder = "NIXPACKS"
buildCommand = "npm install --ignore-engines && npm run build"

[deploy]
startCommand = "npm run migrate:production && npm run start"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3
